import type { Course } from "../lib/type"

export const courses: Course[] = [
  {
    id: 1,
    title: "Solidity Smart Contract Development",
    description: "Learn to build secure and efficient smart contracts on Ethereum",
    level: "Intermediate",
    duration: "8 weeks",
    modules: 12,
    credentials: "Verified Smart Contract Developer",
    category: "smart-contracts",
  },
  {
    id: 2,
    title: "Blockchain Fundamentals",
    description: "Master the core concepts of blockchain technology",
    level: "Beginner",
    duration: "6 weeks",
    modules: 10,
    credentials: "Blockchain Foundation Certificate",
    category: "blockchain",
  },
  {
    id: 3,
    title: "Web3.js & Ethers.js Mastery",
    description: "Build decentralized applications with JavaScript libraries",
    level: "Intermediate",
    duration: "5 weeks",
    modules: 8,
    credentials: "Web3 Developer Certificate",
    category: "web3",
  },
  {
    id: 4,
    title: "DeFi Protocol Development",
    description: "Create your own decentralized finance applications",
    level: "Advanced",
    duration: "10 weeks",
    modules: 15,
    credentials: "DeFi Architect Certificate",
    category: "defi",
  },
  {
    id: 5,
    title: "Zero-Knowledge Proofs",
    description: "Implement privacy-preserving solutions with ZK proofs",
    level: "Advanced",
    duration: "7 weeks",
    modules: 9,
    credentials: "ZK Developer Certificate",
    category: "blockchain",
  },
  {
    id: 6,
    title: "Smart Contract Security & Auditing",
    description: "Learn to identify and fix vulnerabilities in smart contracts",
    level: "Advanced",
    duration: "8 weeks",
    modules: 12,
    credentials: "Smart Contract Security Expert",
    category: "smart-contracts",
  },
]

